name: "CI"
on:
    pull_request:
env:
    USER: runner
    DEV_SHELL_NAME: CI
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.4.0
              with:
                  fetch-depth: 0
            - name: "Setup env"
              uses: JRMurr/direnv-nix-action@c93aad6edb5767e98bc0f312ba9c6f2711da1796

            # This only caches the npm cache dir not the actual node modules
            # caching node modules is not recommended https://github.com/actions/cache/blob/main/examples.md#node---npm
            - name: Get npm cache directory
              id: npm-cache-dir
              run: |
                  echo "::set-output name=dir::$(npm config get cache)"

            - name: use npm cache
              uses: actions/cache@v3
              id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
              with:
                  path: ${{ steps.npm-cache-dir.outputs.dir }}
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: install node modules
              run: npm ci
              shell: bash
            - name: type check
              run: just type-check
              shell: bash
